# docker-compose.yml
version: "3"
services:
  kali:
    build:
      args:
        - KALI_USER=kalidemo
        - KALI_PASSWORD=kalidemo
      context: .
    ports:
      - "3390:3390"
    tty: true
    stdin_open: true
    container_name: kali_container
    restart: unless-stopped
    environment:
      - KALI_USER=kali
      - KALI_PASSWORD=kaliroot
