version: "3"

networks:
  proxy:
    external: true

services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    volumes:
      - ./mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      VIRTUAL_HOST: mailpit.local
      LETSENCRYPT_HOST: mailpit.local
      VIRTUAL_PORT: 8025
      MP_UI_AUTH: "rutvik:Admin@123 admin:Admin@123"
      MP_SMTP_AUTH: "rutvik:Admin@123 admin:Admin@123"
    networks:
      - proxy

