services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Optional: If you use a private registry, mount your Docker config file make sure path is correct like /home/ubuntu/.docker/config.json:/config.json
      - /home/ubuntu/.docker/config.json:/config.json:ro
    environment:
      - WATCHTOWER_POLL_INTERVAL="10"
    command: --debug --cleanup
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
