version: "3.5"

services:
  adminer:
    image: adminer
    restart: always
    # ports:
    #   - 8080:8080
    networks:
      - proxy
    # environment:
    # VIRTUAL_HOST: dummy.adminer.local
    # LETSENCRYPT_HOST: dummy.adminer.local
    # VIRTUAL_PORT: 8080
    # ADMINER_DESIGN: 'pepa-linha-dark'
    labels:
      caddy: "dummy.adminer.local"
      caddy.reverse_proxy: "{{upstreams 8080}}"

networks:
  proxy: { external: true }

