apiVersion: v1
kind: Service
metadata:
  name: go-server-manager-service
spec:
  selector:
    app: go-server-manager
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 31111
      name: go-server
    - protocol: TCP
      port: 5432
      nodePort: 32222
      name: postgres-db
    - protocol: TCP
      port: 8080
      nodePort: 31112
      name: adminer
  type: NodePort

