apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-server-manager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
#    for basic auth
#    nginx.ingress.kubernetes.io/auth-type: basic
#    nginx.ingress.kubernetes.io/auth-secret: go-server-manager-basic-auth
#    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - go-server-manager'
spec:
  ingressClassName: nginx
  rules:
    - host: dummy.adminer.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: go-server-manager-service
                port:
                  number: 8080
          - path: /site(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: go-server-manager-service
                port:
                  name: go-server
